// JavaScript Document
$(function(){
	$(".one").show();
	$(".img1").hide();
	$(".img2").hide();
	$(".img3").hide();
	$(".img4").hide();
	$(".img5").hide();
	$(".img6").hide();
	$(".img7").hide();
	$(".img8").hide();     
	$(".img9").hide();
	$(".img10").hide();
	$(".img11").hide();
	$(".img12").hide();
	$(".one_one").mouseover(function(){
		$(".img1").show();
		});
	$(".one_one").mouseout(function(){
		$(".img1").hide();
		});
	$(".one_two").mouseover(function(){
		$(".img2").show();
		});
	$(".one_two").mouseout(function(){
		$(".img2").hide();
		});	
	$(".one_three").mouseover(function(){
		$(".img3").show();
		});
	$(".one_three").mouseout(function(){
		$(".img3").hide();
		});
	$(".one_four").mouseover(function(){
		$(".img4").show();
		});
	$(".one_four").mouseout(function(){
		$(".img4").hide();
		});
	$(".two_one").mouseover(function(){
		$(".img5").show();
		});
	$(".two_one").mouseout(function(){
		$(".img5").hide();
		});
	$(".two_two").mouseover(function(){
		$(".img6").show();
		});
	$(".two_two").mouseout(function(){
		$(".img6").hide();
		});
	$(".two_three").mouseover(function(){
		$(".img7").show();
		});
	$(".two_three").mouseout(function(){
		$(".img7").hide();
		});
	$(".two_four").mouseover(function(){
		$(".img8").show();
		});
	$(".two_four").mouseout(function(){
		$(".img8").hide();
		});
	$(".three_one").mouseover(function(){
		$(".img9").show();
		});
	$(".three_one").mouseout(function(){
		$(".img9").hide();
		});
	$(".three_two").mouseover(function(){
		$(".img10").show();
		});
	$(".three_two").mouseout(function(){
		$(".img10").hide();
		});
	$(".three_three").mouseover(function(){
		$(".img11").show();
		});
	$(".three_three").mouseout(function(){
		$(".img11").hide();
		});
	$(".three_four").mouseover(function(){
		$(".img12").show();
		});
	$(".three_four").mouseout(function(){
		$(".img12").hide();
		});
	/*$(".one_one").hide();
	$(".one_two").hide();
	$(".one_three").hide();
	$(".one_four").hide();*/
	$(".change1").show();
	$(".change2").show();
	$(".two").hide();
	$(".three").hide();
	$(".change1").click(function(){
		$(".one").hide();
		$(".one_one").hide();
		$(".one_two").hide();
		$(".one_three").hide();
		$(".one_four").hide();
		$(".change1").hide();
		$(".change2").hide();
		$(".two").hide();
		$(".three").show();
		
			$(".change5").click(function(){
				$(".one").hide();
				$(".one_one").hide();
				$(".one_two").hide();
				$(".one_three").hide();
				$(".one_four").hide();
				$(".change1").hide();
				$(".change2").hide();
				$(".two").show();
				$(".three").hide();
					
				});
			$(".change6").click(function(){
				$(".one").show();
				$(".one_one").show();
				$(".one_two").show();
				$(".one_three").show();
				$(".one_four").show();
				$(".change1").show();
				$(".change2").show();
				$(".two").hide();
				$(".three").hide();
				});
					$(".change3").click(function(){
					$(".one").show();
					$(".one_one").show();
					$(".one_two").show();
					$(".one_three").show();
					$(".one_four").show();
					$(".change1").show();
					$(".change2").show();
					$(".two").hide();
					$(".three").hide();
					});
					$(".change4").click(function(){
					$(".one").hide();
					$(".one_one").hide();
					$(".one_two").hide();
					$(".one_three").hide();
					$(".one_four").hide();
					$(".change1").hide();
					$(".change2").hide();
					$(".two").hide();
					$(".three").show();
					});
		
		});
	$(".change2").click(function(){
		$(".one").hide();
		$(".one_one").hide();
		$(".one_two").hide();
		$(".one_three").hide();
		$(".one_four").hide();
		$(".change1").hide();
		$(".change2").hide();
		$(".two").show();
		$(".three").hide();
		
			$(".change3").click(function(){
			$(".one").show();
			$(".one_one").show();
			$(".one_two").show();
			$(".one_three").show();
			$(".one_four").show();
			$(".change1").show();
			$(".change2").show();
			$(".two").hide();
			$(".three").hide();
			});
			$(".change4").click(function(){
			$(".one").hide();
			$(".one_one").hide();
			$(".one_two").hide();
			$(".one_three").hide();
			$(".one_four").hide();
			$(".change1").hide();
			$(".change2").hide();
			$(".two").hide();
			$(".three").show();
			});
				$(".change5").click(function(){
				$(".one").hide();
				$(".one_one").hide();
				$(".one_two").hide();
				$(".one_three").hide();
				$(".one_four").hide();
				$(".change1").hide();
				$(".change2").hide();
				$(".two").show();
				$(".three").hide();
				});
				$(".change6").click(function(){
				$(".one").show();
				$(".one_one").show();
				$(".one_two").show();
				$(".one_three").show();
				$(".one_four").show();
				$(".change1").show();
				$(".change2").show();
				$(".two").hide();
				$(".three").hide();
				});
		});
	
	});