DROP TABLE IF EXISTS admin;
CREATE TABLE `admin` (  `id` int(10) NOT NULL auto_increment,  `admin` varchar(20) NOT NULL,  `password` varchar(30) NOT NULL,  PRIMARY KEY  (`id`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
INSERT INTO admin VALUES('1','lianghuanna','123456');
DROP TABLE IF EXISTS admin_replay;
CREATE TABLE `admin_replay` (  `id` int(5) NOT NULL auto_increment,  `admin` varchar(30) NOT NULL,  `replay_time` varchar(30) NOT NULL,  `replay_content` text NOT NULL,  `user_message_id` varchar(10) NOT NULL,  PRIMARY KEY  (`id`)) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;
INSERT INTO admin_replay VALUES('1','绿子小姐','2016-7-29','我来回复啦。','9');
INSERT INTO admin_replay VALUES('8','','2016-08-04 20:24:45','哈哈。','54');
INSERT INTO admin_replay VALUES('7','','2016-08-02 10:49:09','哈哈。','8');
INSERT INTO admin_replay VALUES('5','','2016-07-31 21:03:12','哈哈哈。','51');
INSERT INTO admin_replay VALUES('9','','2016-08-07 15:35:12','哈哈哈。','52');
INSERT INTO admin_replay VALUES('10','','2016-09-06 21:02:53','hahh','59');
INSERT INTO admin_replay VALUES('11','','2016-09-10 17:58:17','很好听。','72');
DROP TABLE IF EXISTS lm;
CREATE TABLE `lm` (  `id` int(5) NOT NULL auto_increment,  `lm1` varchar(20) NOT NULL,  `lm2` varchar(20) NOT NULL,  `lm3` varchar(20) NOT NULL,  `lmid` int(5) NOT NULL,  PRIMARY KEY  (`id`)) ENGINE=MyISAM AUTO_INCREMENT=84 DEFAULT CHARSET=utf8;
INSERT INTO lm VALUES('2','中国的新闻','','','0');
INSERT INTO lm VALUES('5','','台湾新闻','','2');
INSERT INTO lm VALUES('6','','北京新闻','','2');
INSERT INTO lm VALUES('7','','','朝阳区','6');
INSERT INTO lm VALUES('44','湖南新闻','','','0');
INSERT INTO lm VALUES('45','','电台新闻','','44');
INSERT INTO lm VALUES('49','上海新闻','','','0');
INSERT INTO lm VALUES('80','最新消息','','','0');
INSERT INTO lm VALUES('74','','','嘿嘿嘿','73');
INSERT INTO lm VALUES('83','','新闻类','','80');
INSERT INTO lm VALUES('81','','我的动态','','80');
INSERT INTO lm VALUES('82','','心声','','80');
DROP TABLE IF EXISTS news;
CREATE TABLE `news` (  `id` int(5) NOT NULL auto_increment,  `lm1` varchar(20) NOT NULL,  `lm2` varchar(20) NOT NULL,  `lm3` varchar(20) NOT NULL,  `title` varchar(20) NOT NULL,  `content` text NOT NULL,  `time` varchar(20) NOT NULL,  `hit` int(20) NOT NULL,  `adduser` varchar(20) NOT NULL,  PRIMARY KEY  (`id`)) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;
INSERT INTO news VALUES('31','80','81','0','碎言碎语','        <p>\r\n	  15岁觉得游泳难，放弃游泳，到18岁遇到一个你喜欢的人约你去游泳，你只好说“我不会”；18岁觉得英文难，放弃英文，28岁出现一个很棒但要会英文的工作，你只好说“我不会”。人生前期越嫌麻烦，越懒得学，后来就越可能错过让你动心的人和事，错过新风景！\r\n</p>\r\n<p>\r\n	  有的人你可能认识了一辈子却忽视了一辈子；有的人你也许只见了一面却影响了一生；有的人默默的守在你身边为你付出却被冷落；有的人无心的一个表情却成了你永恒的牵挂，我们常常是努力珍惜未得到的，而遗忘了已拥有的。不要向远方寻找幸福，它也许就在你的手中，你只要安然，握住。\r\n</p>\r\n<p>\r\n	  每个人都会有一段异常艰难的时光，生活的窘迫，工作的失意，学业的压力，爱的惶惶不可终日。挺过来的，人生就会豁然开朗；挺不过来的，时间也会教会你怎么与它们握手言和，所以你都不必害怕的。\r\n</p>\r\n<p>\r\n	 有一天当你发现疏远和拉黑的可能是曾经最聊得来的朋友；背后指责你说你不好的可能是你过去最亲密的伙伴；出手阻碍你的或许是你当初的合伙人；你才会明白，这个世界没有什么是不变的，这个时代，因为利益会有许多人做出许多你想不到的事。沙里淘金后，你才知道原来身边一直对你好的人有多珍贵。\r\n</p>\r\n<p>\r\n	 生活的坑都是自己挖的！譬如，听别人讲话，听到最后，耳朵里只会记住两类话：最愿意听的和最不愿意听的。然后，喜欢听的未必化成快乐，但不喜欢听的一定化成了痛苦，其他的都化成了风。\r\n</p>\r\n<p>\r\n	  时隔多年，本来以为已经豪不介怀，当真正的真相被揭开，却再也找不着可以原谅的理由\r\n</p>\r\n<p>\r\n	 不到万不得已的时候，谁又会想重新开始！曾经经受过的煎熬折磨猜疑失望，通通都要再来一次。重新认识新的人，适应新的环境，以前说过的有趣无趣的话都得重复着再说，温故却不知新。有些事情真的跟勇敢毫无关系，仅仅是因为难以为继。对某些事物和人的眷恋不是不再了，只是那份眷恋，真的走投无路了。<br />\r\n\r\n</p>','2016-09-10 13:03:21','3','绿子小姐');
INSERT INTO news VALUES('32','80','81','0','南方没有姑娘','&nbsp;&nbsp; 赵婉婉跟在乔嘉木后面，只能看到乔嘉木的后脑勺和干净的短发，白色T恤和牛仔裤，还是那样清瘦修长，微微侧过的脸也还是那样眉目如画，一副清净淡然的样子\r\n仿佛这么些年他都没有食过人间烟火，没有被北京汹涌的人群和恐怖的地铁和令人咋舌的房价，变成一个头发油腻笑容世故的怪蜀黍。\r\n　<br />\r\n　&nbsp; 赵婉婉拖着箱子跟在乔嘉木后面胡思乱想，冷不防就看到乔嘉木蹲下来问小区门口一位水果摊的大叔：“这姑娘怎么卖的？”大叔头也不抬：“十块。”\r\n　<br />\r\n　 &nbsp; 乔嘉木从裤兜里掏出十块钱，就买了一斤姑娘。姑娘？ <br />\r\n　　“这个，叫做姑娘？”“嗯。”“姑娘的姑，姑娘的娘？” <br />\r\n　　乔嘉木笑出了声，抬起他那双颠倒众生的丹凤眼瞄了赵婉婉一下，“姑娘。”\r\n　 <br />\r\n　　这是赵婉婉第一次听见有一种水果名字叫做姑娘，一颗颗绿色的小果子，外面是一层皱皱的软软的皮，剥开来是饱满的果实，有点像赵婉婉家乡里一种叫做野辣椒的野草果实。尝起来，味道淡淡的，没有那么酸也没有那么甜，跟这个暧昧的名字比，一点都不够叫人惊艳。 <br />\r\n　　这也是毕业五年后，赵婉婉第一次和乔嘉木联系，第一次和乔嘉木见面。 <br />\r\n　　“来北京出差？”“啊？哦，嗯。”赵婉婉茫然地应着，不自觉地露出个尴尬的笑容。其实不是来北京出差，只是某天她毫无头绪地就给那个她倒背如\r\n流的号码发了条短信：“我下周来北京，有空招待吗？”赵婉婉等了好久都没有收到回复，不由得嘲笑自己，都五年了，他肯定是换了号码。却没想到，半夜里迷糊\r\n间突然听到短信响，平日里睡得沉的她一个激灵爬起来摸到手机，只短短几个字：“好，到了联系。”于是赵婉婉向单位请了一个星期假，就出现在了乔嘉木面前。\r\n　<br />\r\n　乔嘉木看着赵婉婉那怯怯的眼神，像一只受惊的鹿。都这么多年过去了，她在他面前还是这幅样子，怯生生的，带着点惊疑不定，看向他的时候，一双大大的眼睛也总是雾蒙蒙地带着水汽，好像自己随时都会从她眼前消失一样。<br />','2016-09-10 13:10:19','3','绿子小姐');
INSERT INTO news VALUES('30','80','81','0','PHP代码优化24条真经','<p>\r\n	1.echo比print快。\r\n</p>\r\n<p>\r\n	2.使用echo的多重参数代替字符串连接。\r\n</p>\r\n<p>\r\n	3.在执行for循环之前确定最大循环数，不要每循环一次都计算最大值，最好运用foreach代替。\r\n</p>\r\n<p>\r\n	4.对global变量，应该用完就unset()掉。\r\n</p>\r\n<p>\r\n	5.用单引号代替双引号来包含字符串，这样做会更快一些。因为PHP会在双引号包围的字符串中搜寻变量，单引号则不会。\r\n6.函数代替正则表达式完成相同功能。\r\n</p>\r\n<p>\r\n	7.当执行变量$i的递增或递减时，$i++会比++$i慢一些。这种差异是PHP特有的，并不适用于其他语言，++$i更快是因为它只需要3条指令(opcodes)，$i++则需要4条指令。后置递增实际上会产生一个临时变量，这个临时变量随后被递增。而前置递增直接在原值上递增。\r\n</p>\r\n<p>\r\n	8.使用选择分支语句（switch case）好于使用多个if，else if语句。\r\n</p>\r\n<p>\r\n	9.利用var_dump进行PHP代码调试。如果你在寻找php调试技术，我必须说var_dump应该是你要找的目标，在显示php信息方面这个命令可以满足你的所有需要，而调试代码的多数情况与得到PHP中的数值有关。\r\n</p>\r\n<p>\r\n	10.在包含文件时使用完整路径，解析操作系统路径所需的时间会更少。\r\n</p>\r\n<p>\r\n	11.动辄创建全局数值是一种糟糕的做法，不过有时候实际情况的确又需要这么做。对于数据库表或数据库连接信息使用全局数值是一个不错的想法，但不要在你的PHP代码中频繁使用全局数值。另外，更好的一种做法是把你的全局变量存放在一个config.php文件中。\r\n</p>\r\n<p>\r\n	12.如果你想知道脚本开始执行的时刻，使用$_SERVER[‘REQUEST_TIME’]要好于time()。\r\n</p>\r\n<p>\r\n	13.打开apache的mod_deflate模块。\r\n</p>\r\n<p>\r\n	14.用@屏蔽错误消息的做法非常低效。\r\n</p>\r\n<p>\r\n	15.尽量采用大量的PHP内置函数。\r\n</p>\r\n<p>\r\n	16.递增一个未预定义的局部变量要比递增一个预定义的局部变量慢9至10倍。\r\n</p>\r\n<p>\r\n	17.派生类中的方法运行起来要快于在基类中定义的同样的方法。\r\n</p>\r\n<p>\r\n	18.仅定义一个局部变量而没在函数中调用它，同样会减慢速度（其程度相当于递增一个局部变量）\r\n</p>\r\n<p>\r\n	19.Apache解析一个PHP脚本的时间要比解析一个静态HTML页面慢2至10倍。尽量多用静态HTML页面，少用脚本。\r\n</p>\r\n<p>\r\n	20.正如之前提到的，任何php网站中最重要的部分有99%的可能是数据库。因此，你需要非常熟悉如何正确的使用sql，学会关联表和更多高级的数据库技术。\r\n</p>\r\n<p>\r\n	21.调用带有一个参数的空函数，其花费的时间相当于执行7至8次的局部变量递增操作。\r\n</p>\r\n<p>\r\n	22.当操作字符串并需要检验其长度是否满足某种要求时，你想当然地会使用strlen()函数。此函数执行起来相当快，因为它不做任何计算，只返回zval结构（C的内置数据结构，用于存储PHP变量）中存储的已知字符串长度。\r\n</p>\r\n<p>\r\n	23.并不是所有情况都必须使用面向对象开发，面向对象往往开销很大，每个方法和对象调用都会消耗很多内存。\r\n</p>\r\n<p>\r\n	24.除非脚本可以缓存，否则每次调用时都会重新编译一次。引入一套PHP缓存机制通常可以提升25%至100%的性能，以免除编译开销。\r\n</p>','2016-09-10 12:58:24','3','绿子小姐');
INSERT INTO news VALUES('33','80','81','0','IE6到底哪里不好？你还继续用IE6吗？','<p>\r\n	<strong>你还继续用IE6吗？</strong> \r\n</p>\r\n<p>\r\n	&nbsp; IE6的成功标志着一个时代，一个信息时代的成长。回首这十年，个人计算机发生了巨大的变化，每人一台PC成为了可能。从当年的拨号到宽带；从win98到win7 ；从调制解调器到无线wifi；从右键“目标另存为”到迅雷；从博客到微博....等等等等...兴许某些设计师都放弃了IE6，不再解决bug等问题。因为IE6的这些bug确实会花上我们不少时间和精力。\r\n</p>\r\n<p>\r\n	正因为这些年我们不断的跟IE6磨合，我们的技术也不断的提高。我也常常把IE6当成检验自己设计网页好不好的标准。常用的一个工具就是IETester。\r\n</p>\r\n<p>\r\n	<strong>对IE6说再见！</strong> \r\n</p>\r\n<p>\r\n	&nbsp; IE6也许是您上网的第一个入口，但是我们必须直面它的缺点。2014年4月8日，在Windows XP正式退役时，与之一同退出历史舞台的还有曾经广泛普及的IE6浏览器。\r\n</p>\r\n<p>\r\n	&nbsp; 题外话：作为设计师我仍然不会放弃继续兼容IE6！IE6是检查代码严谨性的一个很好的工具，虽然，曾经无数的抱怨、甚至憎恨。但是只要100个用户群里面有一位用户在使用IE6，你就不得不做好兼容。因为我们就是设计师。\r\n</p>','2016-09-10 13:13:30','3','绿子小姐');
INSERT INTO news VALUES('34','80','81','0','苹果评出iPhone十大最好应用','<p>\r\n	1.VSCO：拍照。\r\n</p>\r\n<p>\r\n	2.BuzzFeed Video：整合BuzzFeed视频。\r\n</p>\r\n<p>\r\n	3.1Password：账号安全。\r\n</p>\r\n<p>\r\n	4.MSQRD：变脸神器。\r\n</p>\r\n<p>\r\n	5.Venmo：轻松还钱。\r\n</p>\r\n<p>\r\n	6.Dark Sky：天气预报。\r\n</p>\r\n<p>\r\n	7.Replay Video Editor：视频编辑。\r\n</p>\r\n<p>\r\n	8.RunKeeper：健身。\r\n</p>\r\n<p>\r\n	9.Camera+：拍照。\r\n</p>\r\n<p>\r\n	10.Jet：在线购物。\r\n</p>','2016-09-10 14:40:34','3','绿子小姐');
DROP TABLE IF EXISTS user_message;
CREATE TABLE `user_message` (  `id` int(5) NOT NULL auto_increment,  `name` varchar(30) NOT NULL,  `time` varchar(30) NOT NULL,  `content` text NOT NULL,  `photo` varchar(40) NOT NULL,  `secret` int(11) NOT NULL default '0',  PRIMARY KEY  (`id`)) ENGINE=MyISAM AUTO_INCREMENT=75 DEFAULT CHARSET=utf8;
INSERT INTO user_message VALUES('60','郑爽','2016-09-10 17:32:27','好好加油。','','1');
INSERT INTO user_message VALUES('74','王凯月','2016-09-10 21:26:24','i love  me~~~','','0');
INSERT INTO user_message VALUES('64','鹿晗。','2016-09-10 17:46:42','今天星期五。','','0');
INSERT INTO user_message VALUES('73','李钟硕。','2016-09-10 19:37:23','这是你吗。','','0');
INSERT INTO user_message VALUES('51','含笑','2016-07-31','么么哒','image/3.jpg','0');
INSERT INTO user_message VALUES('59','李钟硕','2016-09-05 15:13:08','你很可爱。','image/3.jpg','0');
INSERT INTO user_message VALUES('61','李钟硕。','2016-09-10 17:34:06','很高兴认识你。','','0');
INSERT INTO user_message VALUES('62','林俊杰。','2016-09-10 17:34:46','确定过眼神，我遇上对的人。','','0');
INSERT INTO user_message VALUES('63','周杰伦。','2016-09-10 17:35:16','我一路向北，离开有你的城市。','','0');
INSERT INTO user_message VALUES('65','鹿晗。','2016-09-10 17:47:29','好好学习，天天向上。','','1');
INSERT INTO user_message VALUES('66','李钟硕。','2016-09-10 17:49:05','其实真的真的很想你，不是假的假的很想你，很想你。','','0');
INSERT INTO user_message VALUES('67','李钟硕。','2016-09-10 17:49:33','二硕。','image/2.jpg','0');
INSERT INTO user_message VALUES('68','张杰。','2016-09-10 17:50:23','今天我，终于站在这年轻的战场。','up/2015qq.png','0');
INSERT INTO user_message VALUES('69','周杰伦。','2016-09-10 17:51:07','晴天。','','0');
INSERT INTO user_message VALUES('70','林俊杰。','2016-09-10 17:51:34','修炼爱情。','image/6.jpg','0');
INSERT INTO user_message VALUES('71','张杰。','2016-09-10 17:52:04','太阳女神。','image/4.jpg','1');
INSERT INTO user_message VALUES('72','杨丞琳。','2016-09-10 17:52:29','缺氧。','image/5.jpg','0');
